#
# Blog Settings
#
author: Travis Illig
description: "Travis Illig's blog about .NET development and personal interests."
show_description_in_nav: false
url: https://www.paraesthesia.com
title: Travis Illig
subtitle: "Paraesthesia: .NET Development and Some Pictures of My Cat"
gravatar_url: https://s.gravatar.com/avatar/5b473ad19f5781cd5f17a65a670f3b37
subscribe_rss: https://feedproxy.google.com/Paraesthesia
locale: en_US

# Github repositories
github_user: tillig
github_repo_url: https://github.com/tillig/tillig.github.io/

# Twitter
twitter_user: tillig
twitter_tweet_button: true

# Google +
google_user: tillig

# LinkedIn
linkedin_user: tillig

# Disqus Comments
disqus_short_name: paraesthesia
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-1285161-1


#
# Jekyll Settings
#
markdown: kramdown
permalink: /archive/:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num"
exclude: [/Gemfile,/Gemfile.lock,/go.bat,rakefile,README.md]
jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate
